name: "Secrets"
description: "Check for secrets in the code"
branding:
  icon: alert-triangle
  color: blue

inputs:
  php-version:
    description: "PHP Version"
    required: true
    default: 'latest'
  message-level:
    description: "Message level for output 1, 2, 4, 8"
    required: false
    default: 4

runs:
  using: "composite"
  steps:
    - name: "Setup"
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        ini-values: "short_open_tag=1"
        tools: cs2pr

    - name: "Run Secret Scanner"
      shell: bash
      env:
        MSGLEVEL: ${{ inputs.message-level }}
      run: php ${{ github.action_path }}/scanner.php ${{ github.event.number }}
